language: node_js
node_js:
- lts/*
install:
- npm ci
- npm install -g codecov
script:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run build; ./node_modules/.bin/nyc
  report --reporter lcovonly -- -R spec; codecov; fi
before_deploy:
- npm run build
branches:
  only: 
    - master
deploy:
  - provider: releases
    api_key:
      secure: gqgNXqrTBE7sUXYwXVTiQv9pz/5VQroIXDsuCZxuWx4BLcUqd8hOGqA5rn3LIKIqriQAFNLGqeVvOlPixoytHDYBKCcaNlbtSDcl24cHQzxrKvIVVDxaMEYtvB3sLC1I+NzwCczyo+xMtmHHzjdhCTFik4LssuH7K/uPYckqhh7V7zJCQGQq/8z/50hMffa3WpvqzVpUqKDf9lcPxUTfq5h9BIkzxEYSy8Lpr9l1gbUYZzaiGYuypJ2ftf5nkxbMxN+XWaySdHiizP3GYkYP4CyUj4KyUG7dCSmXn8VLzqlstqrylc/qb/Sfgb1rA5bW8ywyCIkPzXhvXnZjLtbKSapSORl90wHC9q2nKIVOH1w8W0LX4Vf02oNEGzRfMb014OXPlrtr7lk1+hASoRyS/qKqE2chvIipsHUmoKu4jAzw49EJg7cjO0LWBLL1whwBJc+G/JE6Ofj6dcImH9yA6nM2mnK6Id4XEXDfiuisZXIEAJXi7I7ZHkqmjwdokFtikVhrxQ/X53cEPWvVJ6l85T5874d6ftS+00Jd31hFyGH/M1in266D5jpyoLFx9L5NMZ/waBh3zRjF8Qggj/8D6TKgII5brFs1INDCML0os/7M/46WEss1k3hL2wCEk+XNAt9gmkqESrsi7ZNmduVwgGzVHpwr9w7TndyGdTue/rM=
    file: README.md
    on:
      tags: true
      repo: Guseyn/node-test-executor
      branch: master
  - provider: npm
    email: guseynism@gmail.com
    api_key:
      secure: ABUJTISTkTVxqJjwZKcrQWvd9akLvDHqnluDM2xYmpVW/xlY6LKX95Ikf/gX98jz9YFiYP4AEmuDJuaMvA30/dxAB1X0eJgYl2HygS5CpXUp0r2aNfmSSALgaoj+ZN8pjnCj7tAiyNSfEeXGVkHvPjWGnbDGxvsn7OzXSUuNMUU26b96y9wKUYTC2FeyZIPsD40LNcUAmiPwf6t7ffrUcE9+7DHzVNRrsVNzlYTcRlSBmjSjiGhrUdqGMugPJqHqy9aTlSpQzmTlEr2N5nTfSvvORBrIGGmF5AeK2+UF6ifyhMpq2twXPRXXb6+xC4McA1Cp1w51ZfpPMnmd8Ad1EgxmDsWwym2+u2Ci7jEhYV7ZGag1+kzpQkuQDUkxKNnmTgPOZjPmyyGELBCF+aI4RkPP5rIrec3xrO/pUsVJ2PYoED38sLSjyzz5nfuOX7Xy0bmNkAITBC1NRcdsql7xZnVAPjamEVhO2dw9iNZAFX6aqCNypmwOT8JYNCfO7e8gfeQEDgc71qJihDXtnUUQiM+6K9DZ1KIi+oeO/GKnFtBCkjpgDwGtuW4RffDlV42oQyaWHUBIFKgJqQf0rv1oEAu7DBJJxUImRvv4i41VBzxxQm98XtmgrWeWVQ7yl004SbQJt24nGkREAvSdP2aOOnkkgaYwBZgiNz4Hnx4l6G4=
    on:
      tags: true
      repo: Guseyn/node-test-executor
      branch: master
