language: node_js
node_js:
- lts/*
install:
- npm ci
- npm install -g codecov
script:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run build; ./node_modules/.bin/nyc
  report --reporter lcovonly -- -R spec; codecov; fi
before_deploy:
- npm run build
deploy:
  - provider: releases
    api_key:
      secure: gqgNXqrTBE7sUXYwXVTiQv9pz/5VQroIXDsuCZxuWx4BLcUqd8hOGqA5rn3LIKIqriQAFNLGqeVvOlPixoytHDYBKCcaNlbtSDcl24cHQzxrKvIVVDxaMEYtvB3sLC1I+NzwCczyo+xMtmHHzjdhCTFik4LssuH7K/uPYckqhh7V7zJCQGQq/8z/50hMffa3WpvqzVpUqKDf9lcPxUTfq5h9BIkzxEYSy8Lpr9l1gbUYZzaiGYuypJ2ftf5nkxbMxN+XWaySdHiizP3GYkYP4CyUj4KyUG7dCSmXn8VLzqlstqrylc/qb/Sfgb1rA5bW8ywyCIkPzXhvXnZjLtbKSapSORl90wHC9q2nKIVOH1w8W0LX4Vf02oNEGzRfMb014OXPlrtr7lk1+hASoRyS/qKqE2chvIipsHUmoKu4jAzw49EJg7cjO0LWBLL1whwBJc+G/JE6Ofj6dcImH9yA6nM2mnK6Id4XEXDfiuisZXIEAJXi7I7ZHkqmjwdokFtikVhrxQ/X53cEPWvVJ6l85T5874d6ftS+00Jd31hFyGH/M1in266D5jpyoLFx9L5NMZ/waBh3zRjF8Qggj/8D6TKgII5brFs1INDCML0os/7M/46WEss1k3hL2wCEk+XNAt9gmkqESrsi7ZNmduVwgGzVHpwr9w7TndyGdTue/rM=
    file: README.md
    on:
      tags: true
      repo: Guseyn/node-test-executor
      branch: master
  - provider: npm
    email: guseynism@gmail.com
    api_key:
      secure: QAIyol5sH60ZcPCWQAF+g6IrCE9xbxnTmZ+3Q+UecFPsZGS3rffL/toMbVptunYGPsavyiIq4mtZ8+8RLWBMdL89EaRiBpKYCK+Tmo7coaGhwh5sSWXFIF63mfrxcnBC7B6+yKawmXAQm99z6Kd4ShdbANSqt4UzQOwFUHHQFWc2QyvGzdY/ZJiRAZeNguAh3J705IA7fohzeGycseBoFf4fB24md4JS/XaqgsZ+Rf0Eio+xV1bMFT4Aibpx+gD0r8wY1X/aLzfsRXAPnokz7RJowzg4ksSDNoIJNrh0RRRdbu2XP9MiocwxdkrmbQPvZI496mJowMTXSbv2L3OPTK7g4VJbfSNfQyujhyVfa2mEgE0vrY4UMavvsBgKM2Y5FpnXzNCG7bjGfXzxgu9gYriiVNJGjFQav1Ia39ndsbWtiLLMTAyyxgL7/A42YmzwQKwqmc19+WJFEg2aD63vRnHIwCGsLbUevq26gR+f6376LxWJthjkaLfiOrl+KBKSh7yRGhc4tmJ0pZ2zLkQPKZvArfJMClIWJMb2L9v3gAX56Lw7LHkPOyrbPBO3kjSFzAStJtisBrZx1RY+HUia9TtNTGc/1pPXk9Z7STCiEiuC/7/ZiiuznrJTvdPBgZBD+lwoKmzFKRG2nYc0j2Ea0DBaZzu2b9pHhJ94rteATe0=
    on:
      tags: true
      repo: Guseyn/node-test-executor
      branch: master
